version: '3.4'

services:
  db:
    image: udemy-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    #command: mysql --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net_udemy
    ports:
      - "3308:3306"
    networks:
      - udemy-networks
  
  restappudemy:
    image: restwithaspnet-api
    build:
      context: .
      dockerfile: RestAppUdemy/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
      # ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5000:80"
      - "5001:443"
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-networks

networks:
  udemy-networks:
    driver: bridge